name: 'Skyline DataMiner Deploy Action'
description: 'The action builds an artifact from your solution and deploys it to your cloud connected DataMiner System.'
branding:
  icon: 'download-cloud'  
  color: 'gray-dark'
env:
    working-directory: ./GitHubAction/Package.Builder 
inputs:
  api-key:  # id of input
    description: 'The API-key generated in the DCP Admin app as authentication for a certain DataMiner System, saved in a GitHub secret'
    required: true
  solution-path:
    description: 'The path to the .sln file of the solution. Atm only DataMiner Automation Script solutions are supported. E.g ./Example/AutomationScript.sln. Required for stages: All and Upload.' 
    required: true
  artifact-name:
    description: 'The chosen name of the artifact. E.g. MyPackageName.  Required for stages: All, Upload and Deploy.'
    required: false
  version:
    description: 'The version number for the artifact. Only required for a release run. Format A.B.C for a stable release or A.B.C-text for a pre-release. Required for stages Upload and All if no build number was provided instead.'
    required: false
  timeout:
    description: 'The maximum time spent on waiting for the deployment to finish in seconds. E.g. 900.'
    required: false
    default: "900"
  stage:
    description: 'The specific stage to run in this action. Possible values are: All, Upload, and Deploy. All will run all 3 stages consecutively.'
    required: false
    default: "All"
  artifact-id:
    description: 'The artifact Id of the artifact that you would like to deploy'
    required: false
  build-number:
    description: 'The build number of a workflow run. Only required for a development run. Required for stages Upload and All if no version was provided instead.'
    required: false
  debug:
    description: 'Option to enable debug logging. Optional'
    required: false
outputs:
  artifact-id:
    description: 'The artifact ID if the artifact has been uploaded'
  
runs:
  using: 'docker'
  image: 'docker://ghcr.io/skylinecommunications/skyline-dataminer-deploy-action:1.0.37'
  args:
    - --api-key
    - ${{ inputs.api-key }}
    - --solution-path
    - ${{ inputs.solution-path }}
    - --artifact-name
    - ${{ inputs.artifact-name }}
    - --version
    - ${{ inputs.version }}
    - --timeout
    - ${{ inputs.timeout }}
    - --stage
    - ${{ inputs.stage }}
    - --artifact-id
    - ${{ inputs.artifact-id }}
    - --build-number
    - ${{ inputs.build-number }}
    - --debug
    - ${{ inputs.debug }}
