name: 'Skyline DataMiner Deploy Action'
description: 'The action builds a DataMiner Application Package from your solution and deploys it to your cloud connected DataMiner System.'
branding:
  icon: 'download-cloud'  
  color: 'gray-dark'
env:
    working-directory: ./GitHubAction/Package.Builder 
inputs:
  api-key:  # id of input
    description: 'The API-key generated in the DCP Admin app as authentication for a certain DataMiner System, saved in a GitHub secret'
    required: true
  solution-path:
    description: 'The path to the .sln file of the solution. Atm only DataMiner Automation Script solutions are supported. E.g ./Example/Script.sln. Required for stages: All and Upload.' 
    required: false
  package-name:
    description: 'The chosen name of the package. E.g. MyPackageName.  Required for stages: All, Upload and Deploy.'
    required: false
  version:
    description: 'The version number for the package (format A.B.C). E.g. 1.0.1.  Required for stages: All, Upload and Deploy.'
    required: false
  timeout:
    description: 'The maximum time spend on waiting for the deployment to finish in seconds. E.g. 900.'
    required: false
    default: "900"
  stage:
    description: 'The specific stage to run in this action. Possible values are: All, Upload, and Deploy. All will run all 3 stages consecutively.'
    required: false
    default: "All"
  artifact-id:
    description: 'The artifact Id of the package that you would like to deploy'
    required: false

outputs:
  artifact-id:
    description: 'The artifact Id of the package has been uploaded'
  
runs:
  using: 'docker'
  image: 'docker://ghcr.io/skylinecommunications/skyline-dataminer-deploy-action:1.0.4'
  args:
    - --api-key
    - ${{ inputs.api-key }}
    - --solution-path
    - ${{ inputs.solution-path }}
    - --package-name
    - ${{ inputs.package-name }}
    - --version
    - ${{ inputs.version }}
    - --timeout
    - ${{ inputs.timeout }}
    - --stage
    - ${{ inputs.stage }}
    - --artifact-id
    - ${{ inputs.artifact-id }}
